### ISSUE TITLE
What does "Skipping because of primer matches with wrong orientation" mean? 

### ISSUE THREAD

**Issue by AlkaffAhamed** [CSB5/GERMS_16S_pipeline#15]
When I run `primer_trimmer.py`, I get a lot of warning messages about “Skipping ___ because of primer matches with wrong orientation”. What does this mean? 

The code that probably caused this situation was in lines 181-183 of `primer_trimmer.py` and it looked like this: 

```
        if pos['fw'] > pos['rv']:
            LOG.info("Skipping %s because of primer matches with wrong orientation" % (seqrec.id))
            Continue
```

**Comment by andreas-wilm** [comment]
Well it's been 6 years, so I'm guessing a bit...This function tries to find the postions of the forward and reverse primer sequence on the target sequence. In any potential match the reverse primer should "come later" in the target sequence then the forward one.  If it doesn't, then something is wrong, so skip this match candidate
